apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::245246852393:role/eksctl-gamezone-nodegroup-gamezone-NodeInstanceRole-C5D9gPAm2jAL
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-18T10:07:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1205"
  uid: d12a1791-1c6a-411e-a615-e041d6c14b87
