apiVersion: apps/v1
kind: Deployment

metadata:
  name: gamezone-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gamezone

  template:
    metadata:
      labels:
        app: gamezone

    spec:
      containers:
      - name: gamezone-container

        image: 245246852393.dkr.ecr.ap-south-1.amazonaws.com/gamezone:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80
